# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  appleScrapByCategory:
    container_name: appleScrapByCategory
    image: appstore_scraping:latest
  appleScrapBySavedID:
    container_name: appleScrapBySavedID
    image: appstore_scraping:latest
  googleScrapBySavedID:
    container_name: googleScrapBySavedID
    image: appstore_scraping:latest
  mobileIndexRankApi:
    container_name: mobileIndexRankApi
    image: appstore_scraping:latest