# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  apple_category_scrap:
    container_name: apple_category_scrap
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
  google_saved_package_scrap:
    container_name: google_saved_package_scrap
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
  mobileIndex_rank_api:
    container_name: mobileIndex_rank_api
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul