# docker-compose -f ./bin/window/docker-compose_appleScrapBySavedID.yml up

version: '3.9'
services:
  appleScrapBySavedID:
    env_file:
      - app.env
    container_name: appleScrapBySavedID
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: python3 starter.py appleScrapBySavedID
    volumes:
      - "/D/1. Workspace/8. Python/appStoreScrap/appstore_scrap:/app"
      - "/D/1. Workspace/8. Python/appStoreScrap/data/images:/images"