# docker-compose -f .\docker-compose_mobileIndex_rank_api.yml up

version: '3.9'
services:
  mobileIndex_rank_api:
    env_file:
      - app.env
    container_name: mobileIndex_rank_api
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: python starter.py mobileIndex_rank_api
    volumes:
      - "/D/1. Workspace/8. Python/appStoreScrap/appstore_scrap:/app"
      - "/D/1. Workspace/8. Python/appStoreScrap/data/images:/images"