# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  google_saved_package_scrap:
    container_name: google_saved_package_scrap
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: python starter.py google_saved_package_scrap
    volumes:
      - "/D/1. Workspace/8. Python/appStoreScrap/appstore_scrap:/app"
      - "/D/1. Workspace/8. Python/appStoreScrap/data/images:/app/resource"