# docker-compose -f /home/appstore/appstore_scraping/bin/docker-compose_appleScrapBySavedID.yml up

version: '3.9'
services:
  appleScrapBySavedID:
    env_file:
      - ../app.env
    container_name: appleScrapBySavedID
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: /bin/sh /app/apps/appleScrap/bin/appleScrapBySavedID/run.sh
    volumes:
      - /home/appstore/appstore_scraping:/app
      - /data/appstore/images:/images