# docker-compose -f .\docker-compose_mobileIndexRankApi.yml up --remove-orphans

version: '3.9'
services:
  mobileIndexAppSearch:
    env_file:
      - ../../app.env
    container_name: mobileIndexAppSearch
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: /bin/sh /app/apps/mobileIndex/bin/mobileIndexRankApi.sh
    volumes:
      - "/D/1. Workspace/1. Arc_Project/appListScrap/appstore_scrap:/app"
      - "/D/1. Workspace/1. Arc_Project/appListScrap/data/images:/images"