# docker-compose -f /home/appstore/appstore_scraping/sample/docker-compose.yml up

version: '3.9'
services:
  apple_category_scrap:
    container_name: apple_category_scrap
    image: appstore_scraping:latest
    environment:
      - ACTION=apple_category_scrap
    volumes:
      - /data/appstore/images:/resource
      - /home/appstore/appstore_scraping/logs:/logs