# docker-compose -f .\docker-compose_googleScrapBySavedID.yml up

version: '3.9'
services:
  googleScrapBySavedID:
    env_file:
      - ../../app.env
    container_name: googleScrapBySavedID
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: /bin/sh /app/apps/googleScrap/bin/googleScrapBySavedID/run.sh
    volumes:
      - "/D/1. Workspace/1. Arc_Project/appListScrap/appstore_scrap:/app"
      - "/D/1. Workspace/1. Arc_Project/appListScrap/data/images:/images"
    