# docker-compose -f /home/appstore/appstore_scraping/apps/googleScrap/docker-compose/docker-compose.yml up --remove-orphans

version: '3.9'
services:
  googleScrapBySavedID:
    env_file:
      - ../app.env 
    container_name: googleScrapBySavedID
    image: appstore_scraping:latest
    environment:
      - TZ=Asia/Seoul
    command: /bin/sh /app/apps/googleScrap/bin/googleScrapBySavedID/run.sh
    volumes:
      - /home/appstore/appstore_scraping:/app
      - /data/appstore/images:/images
    